### ISSUE TITLE
表示に時間かかりすぎ

### ISSUE THREAD

**Issue by zinntikumugai** [428lab/Website#18]
SSRせずに静的サイトにしてしまうとか?

**Comment by ShinoharaTa** [comment]
SvelteKit でできないか対応中

**Comment by zinntikumugai** [comment]
@ShinoharaTa 
現状SSRの為にサーバーの立ち上げ時間がほぼ占めてるから環境から直す必要があるね

**Comment by ShinoharaTa** [comment]
SSG含めて検討中。
Connpass APIがなかなかCORSのサーバー側対応をしないようで、苦戦。

とりあえずCloudflare worker等を使用してProxyを用意して、そこ経由する？

**Comment by zinntikumugai** [comment]
当時と今はfirebaseもだいぶ変わったから全体的に見直した方が良いかもね
手頃で動かせれば良いや色が強かったし

RSSとConnpassとかを簡素なJSONに集めておいて、それを開くだけにしても良い
高頻度に変更するわけじゃ無いし、トリガーをCronとかWebHookにしても良いぐらい

**Comment by ShinoharaTa** [comment]
順序を検討中

- 3hごとに起動するCron
- 収集して生成したjsonを作成
- Cloudflare pages等に投げる

**Comment by zinntikumugai** [comment]
いいね
どこでcronを動かす？
Cloudflare pagesを選ぶ決め手は何かな？

**Comment by ShinoharaTa** [comment]
現在実装中
Cloudflare workers で用意して
API叩いたらJSON取得するコードを実装中
静的サイトホスティングは Vercel または Cloudflare Pages を予定

理由
- Cf Pages は CDN の特性をフル活用できる
- 閲覧無料枠がとてもでかい
- GitHubとの連携は GitHub Actions に依存しない

**Comment by ShinoharaTa** [comment]
https://github.com/428lab/Website_Aggregate

クローラーはこのリポジトリで進めております

**Comment by zinntikumugai** [comment]
@ShinoharaTa 
はやない？

>Cf Pages は CDN の特性をフル活用できる
閲覧無料枠がとてもでかい
GitHubとの連携は GitHub Actions に依存しない

CFが悪いとは思わないけど、それほど流入あったっけ？
依存しないというところが良い理由がちょっとわからないな

**Comment by zinntikumugai** [comment]
あまりにも大改修されるとメンテナンスに付いてけないからね
せめて(主力メンバーが)合意してからやらないと後からこれじゃだめって作り直しはしんどいよ

**Comment by ShinoharaTa** [comment]
ホスティング先は未定。
connpass の設定は Cloudflare Workers にて15分ごとに収集するように実装完了

**Comment by ShinoharaTa** [comment]
https://428lab-website.pages.dev/
ビルド後のページを Cloudflare pages に移管してみました。
感覚的には表示速度問題なさそう。

Cloudflare上に集約したのは、アカウントなどが分散することを懸念したため。
github workflow 書かずとも管理コンソール上からデプロイ設定もできるため。

**Comment by ShinoharaTa** [comment]
特に返事がなかったので適用しました。
確認した感じはよさそう。

万が一の場合はドメインすぐ戻せるようにしています
